test_lower (__main__.TestStrMethod) ... FAIL
test_upper (__main__.TestStrMethod) ... ok

======================================================================
FAIL: test_lower (__main__.TestStrMethod)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "catching-all-exceptions.py", line 18, in test_lower
    self.assertEqual('Testing'.lower(), 'testING')
AssertionError: 'testing' != 'testING'
- testing
+ testING


----------------------------------------------------------------------
Ran 2 tests in 0.003s

FAILED (failures=1)
